homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 55
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London


# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
    api_password: !secret api_password

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Embedded MQTT Broker
mqtt:

notify: !include notify.yaml

sensor: !include_dir_merge_list sensors

media_player:
  - platform: samsungtv
    name: Adams TV
    host: 192.168.1.170
  - platform: snapcast
    host: 192.168.1.60
  - platform: mpd
    host: 192.168.1.60
    location: Multi-Room
  - platform: mpd
    host: 192.168.1.61
    location: Den
  - platform: mpd
    host: 192.168.1.62
    location: Bedroom

device_tracker:
  - platform: luci
    host: 192.168.1.1
    username: !secret luci_user
    password: !secret luci_pass
    interval_seconds: 20
    consider_home: 300
    track_new_devices: no

script: !include_dir_named scripts

automation: !include_dir_merge_list automation
