- platform: hp_ilo
  host: 192.168.1.7
  username: hass
  password: !secret ilo_pass
  monitored_variables:
    - name: Server Uptime
      sensor_type: server_power_on_time
      unit_of_measurement: minutes
