# Temp and Humidity Monitoring
- platform: mqtt
  state_topic: 'tortoise/sensor1'
  name: 'Temperature 1'
  unit_of_measurement: '°C'
  value_template: '{{ value_json.temperature }}'
- platform: mqtt
  state_topic: 'tortoise/sensor1'
  name: 'Humidity 1'
  unit_of_measurement: '%'
  value_template: '{{ value_json.humidity }}'

- platform: mqtt
  state_topic: 'tortoise/sensor2'
  name: 'Temperature 2'
  unit_of_measurement: '°C'
  value_template: '{{ value_json.temperature }}'
- platform: mqtt
  state_topic: 'tortoise/sensor2'
  name: 'Humidity 2'
  unit_of_measurement: '%'
  value_template: '{{ value_json.humidity }}'

