- alias: RSS Alert
  trigger:
    - platform: event
      event_type: feedreader
  action:
    - service: notify.adams_android
      data:
        title: 'New RSS Post!'     
        message: "{{ trigger.event.data.content }}"
